config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :users, :only => [:index, :show]

  get '/auth/:provider/callback' => 'sessions#create'

  #match 'contact' => 'inquiries#new', via: 'get'

  #match 'sigin', to: 'sessions#new', :as => :signin
  get '/signin' => 'sessions#new', :as => :signin



  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
  get '/github' => 'github#index'



  match 'about', to: 'pages#about', via: 'get'
  match 'contact', to: 'pages#contact', via: 'get'
end

app/models/github_profile.rb
class GithubProfile < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	#Associate each profile with its user
	has_one :github_profile

  def self.create_with_omniauth(auth)
    new_user= create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end

  	new_user.create_github_profile auth

  	new_user
  end

  def create_github_profile auth
  	GithubProfile.create({user_id: id, nickname: auth[:info][:nickname]|| "", 
  		email: auth[:info][:email]||"", name: auth[:info][:name]||"",
  		image: auth[:info][:image]||"", 
  		location: auth[:extra][:raw_info][:location]||"", 
  		public_repo: auth[:extra][:raw_info][:public_repos]||"",
  		public_gists: auth[:extra][:raw_info][:public_gists]||"",
  		followers: auth[:extra][:raw_info][:followers]||"",
  		following: auth[:extra][:raw_info][:following]||"",
  		member_since: auth[:extra][:raw_info][:created_at]||"",
  		access_token: auth[:credentials][:token]
  		})
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/github_controller.rb
class GithubController < ApplicationController
	#this controller displays the current user repos
	#pull the list of all public repos for the current user
	#first authenticate the client with access token stored in GithubProfile model
	#after that query the user repos with the client.repos
  def index
  	client= Octokit::Client.new(:access_token => current_user.github_profile.access_token)
  	@repositories = client.repos
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about 
	end 

	def contact
	end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/github'
  end

  #extract provider name e.g. github  and the unique id of the user of this provider
  #if there is no user with this params, it will create a new user using the create_with_omniauth mothod
  #in user model
  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/views/github/index.html.erb
<!-- display the basic information for the current user's public repositories-->
<div class="container">
	<table class="table table-responsive table-bordered table-hover table-condensed">
		<caption><%= current_user.name %>'s public repositories</caption>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Watchers</th>
			<th>Forks</th>
			<th>Stargazers</th>
		</tr>
		<% @repositories.each do |repo|%>
		<tr>
			<td><strong><%= repo[:name].capitalize %></strong></td>
			<td><em><%= repo[:description]%></em></td>
			<td><%= repo[:watchers] %></td>
			<td><%= repo[:forks]%></td>
			<td><%= repo[:stargazers_count] %></td>
		</tr>
		<% end%>
	</table>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li>
	<%= link_to 'About', about_path, class:'navbar-brand' %>
</li>
<li>
	<%= link_to 'Contact', contact_path %>
</li>
<% unless current_user %>
	<li>
		<%= link_to "Sign in with Github", signin_path %>
	</li>

<% else %>
	<li>
		<%= link_to "Github profile", "/github" %>
	</li>
<li>
	<%= link_to "Sign out", "/signout"%>
</li>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rsg Github Gem" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rsg Github Gem" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= yield %>
      <%= render 'layouts/messages' %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<% content_for :title do %>About<% end %>
	<h3>About the Website</h3>
	<p>
	This web application was created with
	<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
	from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
	</p>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<p>
		If you experience difficulties using this application, please contact <%= link_to('Elvyn Mejia.', 'http://www.elvynmejia.com/') %>
	</p>
</div>	

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<% if current_user %>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h4 style="text-align:center;">Welcome, <%= current_user.name %></h4>
			<img class="github-profile-image img-responsive img-circle" 
				src="<%= current_user.github_profile.image %>">
		</div>
		<div class="col-md-6" style="margin-top:10px">
			<table class="table table-striped table-hover">
				  <caption>Basic user profile</caption>
				 <tr>
				    <td>From: <%= current_user.github_profile.location %></td>
				</tr>
				<tr>
				    <td>Public repos: <%= current_user.github_profile.public_repo%></td> 
				</tr>
				<tr>
				    <td>Public Gists: <%= current_user.github_profile.public_gists %></td>
				</tr>
				<tr>
				    <td>Followers: <%= current_user.github_profile.followers %></td>
				</tr>
				<tr>
				    <td>Following: <%= current_user.github_profile.following %></td> 
				</tr>
			</table>
		</div>
	</div>
</div>

<% else %>

<div class="container">
	<div class="jumbotron">	
		<div class="container">
			<h1 id="welcome">Welcome!</h1>
			<p id="intro">
				This is a simple <em style="color:#d9534f">GitHub application</em>. Signin with your Github username and password.
				</br>
				This application uses the 	
				<%= link_to('Octokit client', 'https://github.com/octokit/octokit.rb/') %>
				to create access tokens to authenticate and make simple APIs requests on behalf of users. 
			</p>
			<p id="signin"><a class="btn btn-primary" role="button" href=<%= signin_path%>> Signin with Github</a></p>
			<p id="signin"><a class="btn btn-primary" role="button" href=<%= signin_path%>> Signin</a></p>
		</div>
	</div><!--end jumbotron-->

	
	<div class="row">
		<div class="col-md-6">
			<p>(0). Simple example usage.</p>
			<%= image_tag("front1.jpg", :alt => "Example usage screenshot", class: "img-responsive", class: "img-thumbnail") %> 
		</div>
		<div class="col-md-6">
			<p>(1).  Signin using your GitHub credentials.</p>
			<%= image_tag("login1.jpg", :alt => "Login with GitHub credentials screenshot", class: "img-responsive", class: "img-thumbnail") %> 
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<p>(2).  Display basic profile information.</p>
			<%= image_tag("profile1.jpg", :alt => "GitHub profile screenshot", class: "img-responsive", class: "img-thumbnail") %> 
		</div>
		<div class="col-md-6">
			<p>(3). Display public repositories.</p>
				<%= image_tag("repos1.jpg", :alt => "public repos screenshot", class: "img-responsive", class: "img-thumbnail") %> 
		</div>
	</div>
</div><!--close container-->
<% end %>